In [1]:
# Import modules
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import pickle
import ast
import ipynb.fs.full.petal_assistant as pa

# Create a dataset with only the permutations and signa

In [2]:
petal_knot_table = pd.read_csv("finished_petalKnotTable_e2.csv")
petal_knot_table

,permutation,PD_code,Jones_polynomial,Jones_polynomial_span,Alexander_polynomial,Alexander_polynomial_span,Signature,Determinant
0,"[-0.24083, -0.00188772, -1.07326, 1.17663, -0....","[[16, 1, 17, 2], [24, 5, 25, 6], [29, 3, 30, 2...","[[-13, 1], [-12, -3], [-11, 2], [-10, 4], [-9,...",21,"[[-7, -2], [-6, 7], [-5, -14], [-4, 30], [-3, ...",14,0,573
1,"[-1.42823, -0.116308, 0.164929, 1.06284, -0.93...","[[11, 3, 12, 2], [50, 1, 51, 2], [58, 3, 59, 4...","[[-9, -2], [-8, 6], [-7, -7], [-6, -7], [-5, 4...",16,"[[-7, 2], [-6, -11], [-5, 30], [-4, -66], [-3,...",14,-2,2391
2,"[-0.283837, 0.350783, -0.738975, 0.165964, 0.0...","[[24, 4, 25, 3], [55, 5, 56, 4], [72, 1, 73, 2...","[[6, 1], [7, -3], [8, -1], [9, 25], [10, -56],...",24,"[[-11, 1], [-10, -2], [-9, -7], [-8, 38], [-7,...",22,14,4347
3,"[0.825427, 0.429709, 0.661536, -0.537118, -0.9...","[[14, 1, 15, 2], [23, 2, 24, 3], [32, 3, 33, 4...","[[-24, -1], [-23, 3], [-22, -4], [-21, 2], [-2...",18,"[[-9, -1], [-8, 2], [-7, 1], [-6, -4], [-5, 2]...",18,-12,65
4,"[-0.30723, 0.385463, 2.07641, 1.14815, -0.9336...","[[12, 6, 13, 5], [30, 4, 31, 3], [51, 4, 52, 5...","[[-9, 1], [-8, -2], [-7, 3], [-6, -5], [-5, 5]...",8,"[[-2, -2], [-1, 8], [0, -11], [1, 8], [2, -2]]",4,-2,31
...,...,...,...,...,...,...,...,...
49995,"[0.907162, 1.3737, -0.364027, 1.10591, -1.1952...","[[11, 3, 12, 2], [23, 7, 24, 6], [36, 5, 37, 6...","[[-8, 1], [-7, -3], [-6, 5], [-5, -4], [-4, -2...",16,"[[-5, 1], [-4, -5], [-3, 15], [-2, -31], [-1, ...",10,-2,227
49996,"[1.56721, -0.754358, 1.02856, -1.3592, 0.61317...","[[2, 34, 3, 33], [4, 62, 5, 61], [3, 83, 4, 82...","[[-17, -1], [-16, 4], [-15, -5], [-14, 1], [-1...",17,"[[-5, -1], [-4, 3], [-3, 2], [-2, -15], [-1, 2...",10,-6,111
49997,"[0.177757, 0.74981, 0.608532, 0.556874, 0.4317...","[[10, 6, 11, 5], [25, 3, 26, 2], [44, 1, 45, 2...","[[5, -2], [6, 24], [7, -87], [8, 179], [9, -24...",24,"[[-13, -2], [-12, 15], [-11, -61], [-10, 174],...",26,12,80825
49998,"[0.156536, -0.437561, -0.0290161, 1.13743, 1.3...","[[62, 3, 63, 4], [64, 2, 65, 1], [105, 2, 106,...","[[-24, 1], [-23, -11], [-22, 52], [-21, -141],...",25,"[[-7, 2], [-6, -18], [-5, 72], [-4, -204], [-3...",14,-6,8559
49999,"[-0.613498, 0.222341, 0.51451, -1.19699, 0.334...","[[25, 3, 26, 2], [32, 1, 33, 2], [4, 15, 5, 16...","[[0, -1], [1, 3], [2, -4], [3, 6], [4, -5], [5...",8,"[[-3, 1], [-2, -3], [-1, 7], [0, -9], [1, 7], ...",6,2,31

In [3]:
Signatures = petal_knot_table["Signature"]
Permutations = petal_knot_table["permutation"]
Signatures

0         0
1        -2
2        14
3       -12
4        -2
         ..
49995    -2
49996    -6
49997    12
49998    -6
49999     2
Name: Signature, Length: 50000, dtype: int64

In [4]:
keys = [i for i in range(len(Signatures)) if Signatures[i] in range(-5, 5) and Permutations[i][0] == "["]

In [5]:
train_data, test_data = train_test_split(petal_knot_table)

In [6]:
train_signatures = train_data["Signature"]
test_signatures = test_data["Signature"]
train_permutations = train_data["permutation"]
test_permutations = test_data["permutation"]

In [15]:
train_labels = np.array([train_signatures[i] for i in train_signatures.keys() if i in keys])

In [16]:
test_labels = np.array([test_signatures[i] for i in test_signatures.keys() if i in keys])

In [10]:
train_features = pa.process_permutation_dataset([train_permutations[i] for i in train_permutations.keys() if i in keys])

In [12]:
test_features = pa.process_permutation_dataset([test_permutations[i] for i in test_permutations.keys() if i in keys])

In [17]:
small_signature_dataset = (train_features, test_features, train_labels, test_labels)

In [18]:
with open("small_signature_dataset.pkl", "wb") as f:
    pickle.dump(small_signature_dataset, f)